"""add messages and reactions

Revision ID: 658db66b7d17
Revises: 8b03862bd719
Create Date: 2026-05-30 09:16:40.725228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658db66b7d17'
down_revision: Union[str, None] = '8b03862bd719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('message_type', sa.Enum('text', 'image', 'video', 'file', 'audio', name='messagetype'), nullable=True),
    sa.Column('status', sa.Enum('sent', 'delivered', 'read', 'deleted', name='messagestatus'), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('media_name', sa.String(length=255), nullable=True),
    sa.Column('media_size', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
