"""add preferences and crypto columns

Revision ID: c7a5f868f3e8
Revises: 9889161a47ee
Create Date: 2026-05-31 10:33:38.897458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a5f868f3e8'
down_revision: Union[str, None] = '9889161a47ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_bg_type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('chat_bg_value', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('bubble_sent', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('bubble_received', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('font_size', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('dark_mode', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notif_sound', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notif_sound')
    op.drop_column('users', 'dark_mode')
    op.drop_column('users', 'font_size')
    op.drop_column('users', 'bubble_received')
    op.drop_column('users', 'bubble_sent')
    op.drop_column('users', 'chat_bg_value')
    op.drop_column('users', 'chat_bg_type')
    # ### end Alembic commands ###
